// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// ...


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMUQhbi29Zs4ou4h1uP5HvJKDfeckaFmA',
    appId: '1:36125787022:web:1f95db64796eaa72629adf',
    messagingSenderId: '36125787022',
    projectId: 'dima-5b3a5',
    authDomain: 'dima-5b3a5.firebaseapp.com',
    storageBucket: 'dima-5b3a5.appspot.com',
    measurementId: 'G-0JBGM8G935',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5RtmEeoAKFNWTMfEWf4KYoVw8Dr3OwzI',
    appId: '1:36125787022:android:d804c3ab8ed5166d629adf',
    messagingSenderId: '36125787022',
    projectId: 'dima-5b3a5',
    storageBucket: 'dima-5b3a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-I8wagKkb8J57zEYcnawCc_g18P4Q2E',
    appId: '1:36125787022:ios:9857809eb5605477629adf',
    messagingSenderId: '36125787022',
    projectId: 'dima-5b3a5',
    storageBucket: 'dima-5b3a5.appspot.com',
    iosBundleId: 'com.example.dima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz-I8wagKkb8J57zEYcnawCc_g18P4Q2E',
    appId: '1:36125787022:ios:493f577ec350a22e629adf',
    messagingSenderId: '36125787022',
    projectId: 'dima-5b3a5',
    storageBucket: 'dima-5b3a5.appspot.com',
    iosBundleId: 'com.example.dima.RunnerTests',
  );
}
